# Splunk inputs.conf for DC1 (Splunk Server)
# Location: C:\Program Files\Splunk\etc\system\local\inputs.conf

[WinEventLog://Security]
index = main
disabled = 0
sourcetype = WinEventLog:Security

[WinEventLog://System]
index = main
disabled = 0
sourcetype = WinEventLog:System

[WinEventLog://Microsoft-Windows-Sysmon/Operational]
disabled = 0
index = main
sourcetype = XmlWinEventLog:Microsoft-Windows-Sysmon/Operational
